project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Aadarsh Ajikumar"
  
  chapters:
    - index.qmd
    - 1_RemoteSensingIntro.qmd
    - 2_Portfolio.qmd
    - 3_Corrections.qmd
    - 4_Policy.qmd
    - 6_GEE.qmd
    - 7_Classification-I.qmd
    - 9_SAR.qmd

bibliography: references.bib

format:
  html:
    prefer-html: true 
    highlight-style: github
    theme: 
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt


editor: visual

