project:
  type: book

book:
  title: "Learning Diary"
  author: "Aadarsh Ajikumar"
  
  chapters:
    - index.qmd
    - 1_RemoteSensingIntro.qmd
    - 2_Portfolio.qmd
    - 3_Corrections.qmd
    - 4_Policy.qmd
    - 6_GEE.qmd

bibliography: references.bib

format:
  html:
    highlight-style: github
    theme: 
      light: cosmo
      dark: superhero
  pdf:
    documentclass: scrreprt

editor: visual

