project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Aadarsh Ajikumar"
  
  chapters:
    - index.qmd
    - 1_RemoteSensingIntro.qmd
    - 2_Portfolio.qmd
    - 3_Corrections.qmd
    - 4_Policy.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: solar
      dark: materia
  pdf:
    documentclass: scrreprt

editor: visual

